<?php 
session_start();
// var_dump(123);
include("../../config/config.php");
include("../../config/session.php");
include("../../include/function_database_query.php");
include_once(COMMON_FUNCTION_PATH."common_functions.php");

$type='pdf';
function getewaybilldetails($orderData){
	$curl = curl_init();
	$post_data = json_encode($orderData);
	curl_setopt_array($curl, array(
		CURLOPT_URL => "http://ewayasp.webtel.in/EWayBill/v1.3/GetEWB",
		CURLOPT_RETURNTRANSFER => true,
		CURLOPT_ENCODING => "",
		CURLOPT_MAXREDIRS => 10,
		CURLOPT_TIMEOUT => 0,
		CURLOPT_FOLLOWLOCATION => true,
		CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
		CURLOPT_CUSTOMREQUEST => "POST",
		CURLOPT_POSTFIELDS =>$post_data,
		CURLOPT_HTTPHEADER => array(
			"Content-Type: application/json"
		),
	));

	$response = curl_exec($curl);
	$jsonobj = json_decode($response);
	$jsonobj1 = json_decode($jsonobj);
	curl_close($curl);
	return $jsonobj1[0]->EWBDetails;
}
if(strtolower($type) == 'pdf') {
	$invoiceid=$dbcon->real_escape_string($_REQUEST['id']);
	$query="select invoice.* from tbl_invoice as invoice where invoice.invoice_id=$invoiceid";
	$rel=mysqli_fetch_assoc($dbcon->query($query));

	$set="select comp.*,state.state_name,state.gst_state_code from tbl_company as comp left join state_mst as state on comp.stateid=state.stateid where company_id=".$rel['company_id'];
	$set_head=mysqli_fetch_assoc($dbcon->query($set));	

	$company_config = getCompanyConfiguration($dbcon);

	/*$orderData=array(
		'GSTIN'=>$set_head['vatno'],
		'ewbNo'=>$rel['eway_bill_no'],
		'EWBUserName'=>$company_config['ewb_username'],
		'EWBPassword'=>$company_config['ewb_password'],
		'Year'=>date("Y",strtotime($rel['invoice_date'])),
		'Month'=>date("m",strtotime($rel['invoice_date'])),
		'EFUserName'=>EWAY_USERNAME,//webtel provide
		'EFPassword'=>EWAY_PASSWORD,//webtel provide
		'CDKey'=>EWAY_CDKEY
	);*/
	$orderData=array(
		'GSTIN'=>"24AABCC6052G1Z1",
		'ewbNo'=>671520490875,
		'EWBUserName'=>$company_config['ewb_username'],
		'EWBPassword'=>$company_config['ewb_password'],
		'Year'=>2023,
		'Month'=>2,
		'EFUserName'=>EWAY_USERNAME,//webtel provide
		'EFPassword'=>EWAY_PASSWORD,//webtel provide
		'CDKey'=>EWAY_CDKEY
	);

	$ewaydet = getewaybilldetails($orderData);
	$orderArray=json_decode($ewaydet,true);
	// print_r($orderArray);
	$itemarra = $orderArray['itemList'];
	$hsn = '';
	foreach($itemarra as $item){
		$hsn.=$item['hsnCode'].",";
	}
	$vehicledata = $orderArray['VehiclListDetails'];
// print_r($vehicledata);
	$html='';
	$header ='
	<table>
	<tr>
	<td style="border: 0px; text-align: center; font-weight: bold;">Print e-Way Bill / Slip</td>
	</tr>
	</table>';

	$html.='<html>
	<head>					
	<title>e-Way Bill - '.$rel['eway_bill_no'].'</title>

	<style type="text/css">
	/*
	.page{
		width:8.27in;
		height:10.69in;
		}*/
		.nextpage
		{
			page-break-after: always;
		}
		table{
			border-collapse:collapse;
			width:100%;
		}

		table tr,td{
			border:1px solid #000 !important;
			/*page-break-inside:avoid;*/
		}
		.quot_annex_content_div table tr,td{
			padding:5px;
		}
		.blueHeading {
			color: #365f91;
		}

		</style>
		</head>
		<body>
		<!--Show Logo in other pages-->
		<htmlpageheader name="otherpages" style="display:none">
		<div style="text-align:center">'.$header.'</div>
		</htmlpageheader>
		<htmlpagefooter name="otherpages_footer" style="display:none">
		<div style="text-align:center">'.$footer.'</div>
		</htmlpagefooter>
		<sethtmlpageheader name="otherpages" value="on" show-this-page="0"/>
		<div>
		<table>
		<tr style="border-bottom: none; ">
		<td colspan="2" style="border: none; font-weight: bold; text-align: center; background-color: #337ab7; color: #ffffff;">E-Way Bill</td>
		</tr>
		<tr style="border-bottom: none; ">
		<td style="width: 25%; border: none; font-weight: bold;">E-Way Bill No.</td>
		<td style="width: 75%; border: none; font-weight: bold;">: '.$rel['eway_bill_no'].'</td>
		</tr>
		<tr style="border-bottom: none; ">
		<td style="border: none; font-weight: bold;">E-Way Bill Date.</td>
		<td style="border: none; font-weight: bold;">: '.$orderArray['ewayBillDate'].'</td>
		</tr>
		<tr style="border-bottom: none; ">
		<td style="border: none; font-weight: bold;">Generated By</td>
		<td style="border: none; font-weight: bold;">: </td>
		</tr>
		<tr style="border-bottom: none; ">
		<td style="border: none; font-weight: bold;">Valid From</td>
		<td style="border: none; font-weight: bold;">: </td>
		</tr>
		<tr style="border-bottom: none; ">
		<td style="border: none; font-weight: bold;">Valid Until</td>
		<td style="border: none; font-weight: bold;">: '.$orderArray['validUpto'].'</td>
		</tr>
		<tr style="border-bottom: none; ">
		<td colspan="2" style="border: none; font-weight: bold; background-color: #337ab7; color: #ffffff; text-align: center;">Part-A</td>
		</tr>
		<tr style="border-bottom: none; ">
		<td style="border: none; font-weight: bold;">GSTIN of Supplier</td>
		<td style="border: none; font-weight: bold;">: '.$orderArray['fromGstin'].'</td>
		</tr>
		<tr style="border-bottom: none; ">
		<td style="border: none; font-weight: bold;">Place of Dispatch</td>
		<td style="border: none; font-weight: bold;">: '.$orderArray['fromPlace'].'</td>
		</tr>
		<tr style="border-bottom: none; ">
		<td style="border: none; font-weight: bold;">GSTIN of Recipient</td>
		<td style="border: none; font-weight: bold;">: '.$orderArray['toGstin'].'</td>
		</tr>
		<tr style="border-bottom: none; ">
		<td style="border: none; font-weight: bold;">Place of Delivery</td>
		<td style="border: none; font-weight: bold;">: '.$orderArray['toPlace'].'</td>
		</tr>
		<tr style="border-bottom: none; ">
		<td style="border: none; font-weight: bold;">Document No</td>
		<td style="border: none; font-weight: bold;">: '.$orderArray['docNo'].'</td>
		</tr>
		<tr style="border-bottom: none; ">
		<td style="border: none; font-weight: bold;">Document Date</td>
		<td style="border: none; font-weight: bold;">: '.$orderArray['docDate'].'</td>
		</tr>
		<tr style="border-bottom: none; ">
		<td style="border: none; font-weight: bold;">Value of Goods</td>
		<td style="border: none; font-weight: bold;">: '.$orderArray['totalValue'].'</td>
		</tr>
		<tr style="border-bottom: none; ">
		<td style="border: none; font-weight: bold;">HSN Code</td>
		<td style="border: none; font-weight: bold;">: '.trim($hsn,",").'</td>
		</tr>
		<tr style="border-bottom: none; ">
		<td style="border: none; font-weight: bold;">Reason for Transportation</td>
		<td style="border: none; font-weight: bold;">: </td>
		</tr>
		<tr style="border-bottom: none; ">
		<td colspan="2" style="border: none; font-weight: bold; background-color: #337ab7; color: #ffffff; text-align: center;">Part-B</td>
		</tr>
		<tr>
		<td colspan="2" style="border: none;">
		<table style="width: 100%;">
		<tr style="background-color: #a8d3f7; font-weight: bold;">
		<td style="width: 20%; border-right: none;">Mode</td>
		<td style="width: 20%; border-right: none; border-left: none;">Vehicle No</td>
		<td style="width: 20%; border-right: none; border-left: none;">From</td>
		<td style="width: 20%; border-right: none; border-left: none;">Entered Date</td>
		<td style="width: 20%; border-left: none;">Entered By</td>
		</tr>';
		foreach($vehicledata as $vdata){
			$html.='<tr>
			<td style="border-right: none;">'.$orderArray['transMode'].'</td>
			<td style="border-right: none; border-left: none;">'.$vdata['vehicleNo'].'</td>
			<td style="border-right: none; border-left: none;">'.$vdata['fromPlace'].'</td>
			<td style="border-right: none; border-left: none;">'.$vdata['enteredDate'].'</td>
			<td style="border-left: none;"></td>
			</tr>';
		}
		$html.='</table>
		</td>
		</tr>
		</table>';

		$html.='<!--<sethtmlpagefooter name="otherpages_footer" value="on" />-->
		</body>
		</html>';
		// echo $header;
		// echo $html;exit;
		ob_end_clean();
		include("../../view/export/mpdf/mpdf.php");
		$mpdf=new mPDF('','A4','0','calibri','10','10','15','10','1','1');
//		$mdf->SetFont('ProximaNova');
		$mpdf->defaultheaderfontsize = 10; /* in pts */
		$mpdf->defaultheaderfontstyle = B; /* blank, B, I, or BI */
		$mpdf->defaultheaderline = 1; /* 1 to include line below header/above footer */
		$mpdf->defaultfooterfontsize = 10; /* in pts */
		$mpdf->defaultfooterfontstyle = B; /* blank, B, I, or BI */
		$mpdf->defaultfooterline = 1; /* 1 to include line below header/above footer */
		$mpdf->SetHTMLHeader($header);
		$mpdf->SetHTMLFooter($footer);
		$mpdf->SetWatermarkText();
		$mpdf->showWatermarkText = true;
		$mpdf->allow_charset_conversion=true;
		$mpdf->charset_in='UTF-8';
		$mpdf->WriteHTML($html);
		$mpdf->Output();
		//$mpdf->Output('../../view/upload/quotation_pfd/quotation'.$quotation_id.'.pdf','f');
		ob_clean();
		return 'E-Way Bill '.$rel['eway_bill_no'].'.pdf';
	}	
?>