<?php
session_start();
$AJAX = true;
include('../../include/urlfileinner.php');
$incPath = $path.'include/';
include_once(COMMON_FUNCTION_INNER_PATH."finance_common_functions.php");
include_once("../../../include/common_send_email.php");
// include_once("../../../print/view/umaboy_sales_order_print.php");

$companyConfiguration=getCompanyConfiguration($dbcon);

$POST = ($_POST != NULL)? bulk_filter($dbcon,$_POST) : bulk_filter($dbcon,$_GET);


if(strtolower($POST['mode']) == "add") {
	$query = "select * from tbl_sales_order_review_data where review_status=0 and sales_order_id=".$POST['sales_order_id'];
	$result = $dbcon->query();
	$cnt = brp_mysqli_num_rows($result);
	if($cnt>0){
		$arr['msg'] = '-1';
	}else{
		$info['project']											= $POST['project'];
		$info['datasheet']											= $POST['datasheet'];
		$info['our_quotation_ref']									= $POST['our_quotation_ref'];
		$info['legal_requirements']									= $POST['legal_requirements'];
		$info['operating_temperature']								= $POST['operating_temperature'];
		$info['operating_pressure']									= $POST['operating_pressure'];
		$info['fluid_service_application']							= $POST['fluid_service_application'];
		$info['design_mfg_standard']								= $POST['design_mfg_standard'];
		$info['testing_standard']									= $POST['testing_standard'];
		$info['qsl']												= $POST['qsl'];
		$info['qty']												= $POST['qty'];
		$info['required_del_date']									= date('Y-m-d',strtotime($POST['required_del_date']));
		$info['body_bonnet_cover']									= $POST['body_bonnet_cover'];
		$info['gate_ball_disc_plug']								= $POST['gate_ball_disc_plug'];
		$info['seat_ring']											= $POST['seat_ring'];
		$info['steam']												= $POST['steam'];
		$info['stud_nut']											= $POST['stud_nut'];
		$info['back_seat_bush']										= $POST['back_seat_bush'];
		$info['gasket']												= $POST['gasket'];
		$info['packing_seals']										= $POST['packing_seals'];
		$info['end_connection']										= $POST['end_connection'];
		$info['valve_ot']											= $POST['valve_ot'];
		$info['inspection_by']										= $POST['inspection_by'];
		$info['scope_of_inspaction']								= $POST['scope_of_inspaction'];
		$info['applicable_nde']										= $POST['applicable_nde'];
		$info['af_sales_service']									= $POST['af_sales_service'];
		$info['coating_painting_req']								= $POST['coating_painting_req'];
		$info['packing_req']										= $POST['packing_req'];
		$info['making_product']										= $POST['making_product'];
		$info['making_packing']										= $POST['making_packing'];
		$info['api_monogram_making']								= $POST['api_monogram_making'];
		$info['delivery_due_date']									= date('Y-m-d',strtotime($POST['delivery_due_date']));
		$info['customer_contact_detail']							= $POST['customer_contact_detail'];
		$info['delivery_location']									= $POST['delivery_location'];
		$info['documents_submit']									= $POST['documents_submit'];
		$info['payment_terms']										= $POST['payment_terms'];
		$info['insurance']											= $POST['insurance'];
		$info['freight']											= $POST['freight'];
		$info['remark']												= $_POST['remark'];
		$info['bore_type_size']										= $POST['bore_type_size'];
		$info['face_end_dimension']									= $POST['face_end_dimension'];
		$info['intermediate_design_pressure']						= $POST['intermediate_design_pressure'];
		$info['service_compatibillity']								= $POST['service_compatibillity'];
		$info['valve_orentation']									= $POST['valve_orentation'];
		$info['pressure_balance_hole']								= $POST['pressure_balance_hole'];
		$info['end_connectors_type']								= $POST['end_connectors_type'];
		$info['external_loads']										= $POST['external_loads'];
		$info['flow_coefficient_cvkv']								= $POST['flow_coefficient_cvkv'];
		$info['valve_topwork_diamention']							= $POST['valve_topwork_diamention'];
		$info['bto']												= $POST['bto'];
		$info['btc']												= $POST['btc'];
		$info['rto']												= $POST['rto'];
		$info['rtc']												= $POST['rtc'];
		$info['eto']												= $POST['eto'];
		$info['etc']												= $POST['etc'];
		$info['valve_drive_train_mast']								= $POST['valve_drive_train_mast'];
		$info['length_direction_stroke_oc_linear_valve']			= $POST['length_direction_stroke_oc_linear_valve'];
		$info['angle_rotation_partturn_checkvalve']					= $POST['angle_rotation_partturn_checkvalve'];
		$info['direction_rotation_number_multiturn_valve']			= $POST['direction_rotation_number_multiturn_valve'];
		$info['enable_valve_maintain_position']						= $POST['enable_valve_maintain_position'];
		$info['breakaway_anglepercent_stroke']						= $POST['breakaway_anglepercent_stroke'];
		$info['num_turns_manualy_opevalve']							= $POST['num_turns_manualy_opevalve'];
		$info['flange_bolting_studded_outlet_endconnector']			= $POST['flange_bolting_studded_outlet_endconnector'];
		$info['chemcomp_prescontai_controlling_material']			= $POST['chemcomp_prescontai_controlling_material'];
		$info['valve_seat_functionality']							= $POST['valve_seat_functionality'];
		$info['extended_steam_shaft_assemblies']					= $POST['extended_steam_shaft_assemblies'];
		$info['boulting_sour_service']								= $POST['boulting_sour_service'];
		$info['locking_device']										= $POST['locking_device'];
		$info['position_indicator']									= $POST['position_indicator'];
	 	$info['drain']												= $POST['drain'];
		$info['vent']												= $POST['vent'];
		$info['drain_pressure_ventlines']							= $POST['drain_pressure_ventlines'];
		$info['sealant_injection']									= $POST['sealant_injection'];
		$info['drain_vent_injection_valves']						= $POST['drain_vent_injection_valves'];
		$info['paggabillity']										= $POST['paggabillity'];
		$info['welding_overlay_iron_dilution']						= $POST['welding_overlay_iron_dilution'];
		$info['weld_repair_forgings']								= $POST['weld_repair_forgings'];
		$info['pressure_boundary_bolting_hardness_testing']			= $POST['pressure_boundary_bolting_hardness_testing'];
		$info['inservice_field_testing']							= $POST['inservice_field_testing'];
		$info['anti_static_device_test']							= $POST['anti_static_device_test'];
		$info['torque_test']										= $POST['torque_test'];
		$info['fire_safe_test']										= $POST['fire_safe_test'];
		$info['drive_train_strength_test']							= $POST['drive_train_strength_test'];
		$info['supplementry_test']									= $POST['supplementry_test'];
		$info['cavity_relief_test']									= $POST['cavity_relief_test'];
		$info['dbb_valve_test']										= $POST['dbb_valve_test'];
		$info['dib1_test']											= $POST['dib1_test'];
		$info['dib2_seat_test']										= $POST['dib2_seat_test'];
		$info['dib1_dib2_test_valves']								= $POST['dib1_dib2_test_valves'];
		$info['hardness_test']										= $POST['hardness_test'];
		$info['charpy_impact_test']									= $POST['charpy_impact_test']; 
		$info['hic_test']											= $POST['hic_test'];
		$info['high_pressure_gas_test']								= $POST['high_pressure_gas_test']; 
		$info['fugitive_emission_test']								= $POST['fugitive_emission_test'];
		$info['gauge_drift_test']									= $POST['gauge_drift_test'];
		$info['pressure_testing_valve_hydrostatic']					= $POST['pressure_testing_valve_hydrostatic'];
		$info['special_flanges_mechanical_joints']					= $POST['special_flanges_mechanical_joints'];
		$info['thirdparty_witness']									= $POST['thirdparty_witness'];
		$info['hydroshell_nonassembled_cond']						= $POST['hydroshell_nonassembled_cond'];
		$info['corrosion_protection_measures_longterm_storage']		= $POST['corrosion_protection_measures_longterm_storage'];
		$info['external_coating_painting_valves']					= $POST['external_coating_painting_valves'];		
		$info['corrosion_resistant_metalic_surfaces']				= $POST['corrosion_resistant_metalic_surfaces'];
		$info['disassembly_maintainance_tool']						= $POST['disassembly_maintainance_tool'];
		$info['support_rib_legs']									= $POST['support_rib_legs'];
		$info['valve_lifting']										= $POST['valve_lifting'];
		$info['use_assembly_lubricant']								= $POST['use_assembly_lubricant'];
		$info['additional_requirements']							= $POST['additional_requirements'];
		$info['auxilliary_connope']									= $POST['auxilliary_connope'];
		$info['valve_orientation']									= $POST['valve_orientation'];
		$info['hard_facing_body_wedge_guides']						= $POST['hard_facing_body_wedge_guides'];
		$info['bonnet_gaskettype']									= $POST['bonnet_gaskettype'];
		$info['lantern_ring']										= $POST['lantern_ring'];
		$info['chain_wheel_cable']									= $POST['chain_wheel_cable'];
		$info['handwheel_gearbox_actuatortype']						= $POST['handwheel_gearbox_actuatortype'];
		$info['alternate_stem_packing_materials']					= $POST['alternate_stem_packing_materials'];
		$info['bonnet_bolting_material']							= $POST['bonnet_bolting_material'];
		$info['stuffing_box_surface_finish']						= $POST['stuffing_box_surface_finish'];
		$info['valve_paint_color']									= $POST['valve_paint_color']; 
		$info['additional_req']										= $POST['additional_req'];	
		$info['ref_approve_gad']									= $POST['ref_approve_gad'];
		$info['raf_approve_qap']									= $POST['raf_approve_qap'];
		$info['reference_wo']										= $POST['reference_wo'];
		$info['prepared_by']										= $POST['prepared_by'];
		$info['prepared_name']										= $POST['prepared_name'];
		$info['consulted_by1']										= $POST['consulted_by1'];
		$info['consulted_name1']									= $POST['consulted_name1'];
		$info['consulted_by2']										= $POST['consulted_by2'];
		$info['consulted_name2']									= $POST['consulted_name2'];
		$info['review_approve_by']									= $POST['review_approve_by'];
		$info['reviewed_approve_name']								= $POST['reviewed_approve_name'];
		$info['cdate']												= date("Y-m-d H:i:s");
		$info['company_id']											= $_SESSION['company_id'];
		$info['user_id']											= $_SESSION['user_id'];
		$info['sales_order_id']										= $POST['sales_order_id'];
		$info['sales_ordertrn_id']									= $POST['sales_ordertrn_id'];
	   	
	   	$inserid = add_record('tbl_sales_order_review_data', $info, $dbcon,'');

	   	if($inserid){
	   		$arr['msg']  = '1';
	   	}else{
	   		$arr['msg']  = '0';
	   	}
	}
	$arr['back'] = 'sales_order_list';
   	echo json_encode($arr);
}else if(strtolower($POST['mode']) == "edit") {
	
	$info['project']											= $POST['project'];
	$info['datasheet']											= $POST['datasheet'];
	$info['our_quotation_ref']									= $POST['our_quotation_ref'];
	$info['legal_requirements']									= $POST['legal_requirements'];
	$info['operating_temperature']								= $POST['operating_temperature'];
	$info['operating_pressure']									= $POST['operating_pressure'];
	$info['fluid_service_application']							= $POST['fluid_service_application'];
	$info['design_mfg_standard']								= $POST['design_mfg_standard'];
	$info['testing_standard']									= $POST['testing_standard'];
	$info['qsl']												= $POST['qsl'];
	$info['qty']												= $POST['qty'];
	$info['required_del_date']									= date('Y-m-d',strtotime($POST['required_del_date']));
	$info['body_bonnet_cover']									= $POST['body_bonnet_cover'];
	$info['gate_ball_disc_plug']								= $POST['gate_ball_disc_plug'];
	$info['seat_ring']											= $POST['seat_ring'];
	$info['steam']												= $POST['steam'];
	$info['stud_nut']											= $POST['stud_nut'];
	$info['back_seat_bush']										= $POST['back_seat_bush'];
	$info['gasket']												= $POST['gasket'];
	$info['packing_seals']										= $POST['packing_seals'];
	$info['end_connection']										= $POST['end_connection'];
	$info['valve_ot']											= $POST['valve_ot'];
	$info['inspection_by']										= $POST['inspection_by'];
	$info['scope_of_inspaction']								= $POST['scope_of_inspaction'];
	$info['applicable_nde']										= $POST['applicable_nde'];
	$info['af_sales_service']									= $POST['af_sales_service'];
	$info['coating_painting_req']								= $POST['coating_painting_req'];
	$info['packing_req']										= $POST['packing_req'];
	$info['making_product']										= $POST['making_product'];
	$info['making_packing']										= $POST['making_packing'];
	$info['api_monogram_making']								= $POST['api_monogram_making'];
	$info['delivery_due_date']									= date('Y-m-d',strtotime($POST['delivery_due_date']));
	$info['customer_contact_detail']							= $POST['customer_contact_detail'];
	$info['delivery_location']									= $POST['delivery_location'];
	$info['documents_submit']									= $POST['documents_submit'];
	$info['payment_terms']										= $POST['payment_terms'];
	$info['insurance']											= $POST['insurance'];
	$info['freight']											= $POST['freight'];
	$info['remark']												= $_POST['remark'];
	$info['bore_type_size']										= $POST['bore_type_size'];
	$info['face_end_dimension']									= $POST['face_end_dimension'];
	$info['intermediate_design_pressure']						= $POST['intermediate_design_pressure'];
	$info['service_compatibillity']								= $POST['service_compatibillity'];
	$info['valve_orentation']									= $POST['valve_orentation'];
	$info['pressure_balance_hole']								= $POST['pressure_balance_hole'];
	$info['end_connectors_type']								= $POST['end_connectors_type'];
	$info['external_loads']										= $POST['external_loads'];
	$info['flow_coefficient_cvkv']								= $POST['flow_coefficient_cvkv'];
	$info['valve_topwork_diamention']							= $POST['valve_topwork_diamention'];
	$info['bto']												= $POST['bto'];
	$info['btc']												= $POST['btc'];
	$info['rto']												= $POST['rto'];
	$info['rtc']												= $POST['rtc'];
	$info['eto']												= $POST['eto'];
	$info['etc']												= $POST['etc'];
	$info['valve_drive_train_mast']								= $POST['valve_drive_train_mast'];
	$info['length_direction_stroke_oc_linear_valve']			= $POST['length_direction_stroke_oc_linear_valve'];
	$info['angle_rotation_partturn_checkvalve']					= $POST['angle_rotation_partturn_checkvalve'];
	$info['direction_rotation_number_multiturn_valve']			= $POST['direction_rotation_number_multiturn_valve'];
	$info['enable_valve_maintain_position']						= $POST['enable_valve_maintain_position'];
	$info['breakaway_anglepercent_stroke']						= $POST['breakaway_anglepercent_stroke'];
	$info['num_turns_manualy_opevalve']							= $POST['num_turns_manualy_opevalve'];
	$info['flange_bolting_studded_outlet_endconnector']			= $POST['flange_bolting_studded_outlet_endconnector'];
	$info['chemcomp_prescontai_controlling_material']			= $POST['chemcomp_prescontai_controlling_material'];
	$info['valve_seat_functionality']							= $POST['valve_seat_functionality'];
	$info['extended_steam_shaft_assemblies']					= $POST['extended_steam_shaft_assemblies'];
	$info['boulting_sour_service']								= $POST['boulting_sour_service'];
	$info['locking_device']										= $POST['locking_device'];
	$info['position_indicator']									= $POST['position_indicator'];
 	$info['drain']												= $POST['drain'];
	$info['vent']												= $POST['vent'];
	$info['drain_pressure_ventlines']							= $POST['drain_pressure_ventlines'];
	$info['sealant_injection']									= $POST['sealant_injection'];
	$info['drain_vent_injection_valves']						= $POST['drain_vent_injection_valves'];
	$info['paggabillity']										= $POST['paggabillity'];
	$info['welding_overlay_iron_dilution']						= $POST['welding_overlay_iron_dilution'];
	$info['weld_repair_forgings']								= $POST['weld_repair_forgings'];
	$info['pressure_boundary_bolting_hardness_testing']			= $POST['pressure_boundary_bolting_hardness_testing'];
	$info['inservice_field_testing']							= $POST['inservice_field_testing'];
	$info['anti_static_device_test']							= $POST['anti_static_device_test'];
	$info['torque_test']										= $POST['torque_test'];
	$info['fire_safe_test']										= $POST['fire_safe_test'];
	$info['drive_train_strength_test']							= $POST['drive_train_strength_test'];
	$info['supplementry_test']									= $POST['supplementry_test'];
	$info['cavity_relief_test']									= $POST['cavity_relief_test'];
	$info['dbb_valve_test']										= $POST['dbb_valve_test'];
	$info['dib1_test']											= $POST['dib1_test'];
	$info['dib2_seat_test']										= $POST['dib2_seat_test'];
	$info['dib1_dib2_test_valves']								= $POST['dib1_dib2_test_valves'];
	$info['hardness_test']										= $POST['hardness_test'];
	$info['charpy_impact_test']									= $POST['charpy_impact_test']; 
	$info['hic_test']											= $POST['hic_test'];
	$info['high_pressure_gas_test']								= $POST['high_pressure_gas_test']; 
	$info['fugitive_emission_test']								= $POST['fugitive_emission_test'];
	$info['gauge_drift_test']									= $POST['gauge_drift_test'];
	$info['pressure_testing_valve_hydrostatic']					= $POST['pressure_testing_valve_hydrostatic'];
	$info['special_flanges_mechanical_joints']					= $POST['special_flanges_mechanical_joints'];
	$info['thirdparty_witness']									= $POST['thirdparty_witness'];
	$info['hydroshell_nonassembled_cond']						= $POST['hydroshell_nonassembled_cond'];
	$info['corrosion_protection_measures_longterm_storage']		= $POST['corrosion_protection_measures_longterm_storage'];
	$info['external_coating_painting_valves']					= $POST['external_coating_painting_valves'];		
	$info['corrosion_resistant_metalic_surfaces']				= $POST['corrosion_resistant_metalic_surfaces'];
	$info['disassembly_maintainance_tool']						= $POST['disassembly_maintainance_tool'];
	$info['support_rib_legs']									= $POST['support_rib_legs'];
	$info['valve_lifting']										= $POST['valve_lifting'];
	$info['use_assembly_lubricant']								= $POST['use_assembly_lubricant'];
	$info['additional_requirements']							= $POST['additional_requirements'];
	$info['auxilliary_connope']									= $POST['auxilliary_connope'];
	$info['valve_orientation']									= $POST['valve_orientation'];
	$info['hard_facing_body_wedge_guides']						= $POST['hard_facing_body_wedge_guides'];
	$info['bonnet_gaskettype']									= $POST['bonnet_gaskettype'];
	$info['lantern_ring']										= $POST['lantern_ring'];
	$info['chain_wheel_cable']									= $POST['chain_wheel_cable'];
	$info['handwheel_gearbox_actuatortype']						= $POST['handwheel_gearbox_actuatortype'];
	$info['alternate_stem_packing_materials']					= $POST['alternate_stem_packing_materials'];
	$info['bonnet_bolting_material']							= $POST['bonnet_bolting_material'];
	$info['stuffing_box_surface_finish']						= $POST['stuffing_box_surface_finish'];
	$info['valve_paint_color']									= $POST['valve_paint_color']; 
	$info['additional_req']										= $POST['additional_req'];	
	$info['ref_approve_gad']									= $POST['ref_approve_gad'];
	$info['raf_approve_qap']									= $POST['raf_approve_qap'];
	$info['reference_wo']										= $POST['reference_wo'];
	$info['prepared_by']										= $POST['prepared_by'];
	$info['prepared_name']										= $POST['prepared_name'];
	$info['consulted_by1']										= $POST['consulted_by1'];
	$info['consulted_name1']									= $POST['consulted_name1'];
	$info['consulted_by2']										= $POST['consulted_by2'];
	$info['consulted_name2']									= $POST['consulted_name2'];
	$info['review_approve_by']									= $POST['review_approve_by'];
	$info['reviewed_approve_name']								= $POST['reviewed_approve_name'];
	$info['cdate']												= date("Y-m-d H:i:s");
	$info['company_id']											= $_SESSION['company_id'];
	$info['user_id']											= $_SESSION['user_id'];
	$info['sales_order_id']										= $POST['sales_order_id'];
	$info['sales_ordertrn_id']									= $POST['sales_ordertrn_id'];
	   	
   	$inserid = update_record('tbl_sales_order_review_data', $info,"order_review_id=".$POST['order_review_id'], $dbcon);

   	if($inserid){
   		$arr['msg']  = '2';
   	}else{
   		$arr['msg']  = '0';
   	}
   	$arr['back'] = 'sales_order_list';
   	echo json_encode($arr);
}
?>